name: "Support Requests"

on:
  issues:
    types: [labeled, unlabeled, reopened]

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v2
        with:
          issue-comment: >
            :wave: @{issue-author}, we use the issue tracker exclusively for bug reports
            and feature requests. However, this issue appears to be a support request.
            For usage questions, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/react-router)
            or [Reactiflux](https://discord.gg/6RyV8n8yyM) where there are a lot more people ready to help you out.

            Please feel free to clarify your issue if you think it was closed prematurely.
